### ISSUE TITLE
[BUG] This is detectable

### ISSUE THREAD

**Issue by CodeSmithForge** [iamsrikanthnani/pluely#94]
### Platform

macOS

### Pluely Version

mac

### Description

look when you ask a question it just blurs. things like cluely passes it. i only tried urs because urs is multimodal. but your thing is very detectable. It can't even hide window switches. terrible scam.  it says window blur. 

<img width="659" height="268" alt="Image" src="https://github.com/user-attachments/assets/a12f637d-cd35-460c-a36e-57a346ac16bf" />

[focus_visibility_test.html](https://github.com/user-attachments/files/22778147/focus_visibility_test.html)

**Comment by CodeSmithForge** [comment]
please fix

**Comment by iamsrikanthnani** [comment]
Have been trying to fix this for the last two days, still finding a way to fix this properly.

**Comment by iamsrikanthnani** [comment]
Update: this is fixed, and now fully works on macOS even with full screen without any issues.
This will be released in the next version(this Friday).

**Comment by iamsrikanthnani** [comment]
https://github.com/user-attachments/assets/b9670cb1-88c1-4b29-a3fb-2b023abf2d17

**Comment by iamsrikanthnani** [comment]
### 🚀 Pluely v0.1.6 is now available Download it now from [here](https://pluely.com/downloads).

**Comment by rahul0x00** [comment]
@iamsrikanthnani hey srikanth, this issue is still there on windows

**Comment by iamsrikanthnani** [comment]
@rahul0x00 Windows has some limitations. I was trying to fix that in the next version.
